apiVersion: 1
prune: true
deleteDatasources:
  - name: Loki
    orgId: 1
  - name: loki-1
    orgId: 1
  - name: Prometheus
    orgId: 1
datasources:
  - access: proxy
    basicAuth: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "docker"
    editable: true
    isDefault: true
    name: loki
    type: loki
    uid: loki
    url: http://loki:3100
    version: 2

  - access: proxy
    basicAuth: false
    editable: true
    isDefault: false
    name: prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    version: 2