receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
  otlphttp:
    endpoint: http://loki:3100/otlp
    headers:
      X-Scope-OrgID: docker
  debug:
    verbosity: detailed

extensions:
  health_check: {}

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp, debug]

    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus, debug]
  extensions: [health_check]