{
 "title": "Tier Vote",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Server logs",
   "type": "logs",
   "description": "Shows the logs from the tier vote server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"TierVote.Web\"} |= ``"
    }
   ]
  },
  {
   "title": "Total Exceptions in 1hr",
   "type": "stat",
   "description": "Shows the total number of exceptions that occured in the span of 1hr",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_exceptions_total[1h]))",
     "legendFormat": "total exceptions"
    }
   ]
  },
  {
   "title": "Max Active Connections",
   "type": "gauge",
   "description": "Shows the highest number of active connections in the past 5 min",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(signalr_server_active_connections[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Active Elections",
   "type": "stat",
   "description": "Shows the current number of elections that are in the Voting state or Round Calculation state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tiervote_active_elections", "legendFormat": "Active Elections" }
   ]
  },
  {
   "title": "Active Elections Time Series",
   "type": "timeseries",
   "description": "Shows the increases and decreases of active elections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "expr": "tiervote_active_elections", "legendFormat": "Active Elections" }
   ]
  },
  {
   "title": "New Elections 24hr",
   "type": "stat",
   "description": "Shows the number of elections created in the past 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(tiervote_elections_created_total[24h]))"
    }
   ]
  },
  {
   "title": "Elections Created Rate",
   "type": "timeseries",
   "description": "shows the rate of elections created over an hour range",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(tiervote_elections_created_total[15m])",
     "legendFormat": "Rate Elections Created"
    }
   ]
  },
  {
   "title": "Elections Created Per Day",
   "type": "barchart",
   "description": "Shows the increase and decrease in election creations per day",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(tiervote_elections_created_total[1d]))",
     "legendFormat": "Num Elections Created"
    }
   ]
  },
  {
   "title": "Election Duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(tiervote_election_duration_seconds_bucket[1d])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}