apiVersion: v1
kind: Service
metadata:
  name: activitiesapp-api
  namespace: sam-cael-final
spec:
  selector:
    app: activitiesapp-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
