apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: sam-cael-final
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS "Activities" (
      "Id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
      "City" text NOT NULL DEFAULT '',
      "Name" text NOT NULL DEFAULT '',
      "Description" text NOT NULL DEFAULT '',
      "Cost" double precision NOT NULL DEFAULT 0,
      "Activitytime" timestamp NOT NULL DEFAULT NOW(),
      "Latitude" double precision NOT NULL DEFAULT 0,
      "Longitude" double precision NOT NULL DEFAULT 0,
      "MinAge" integer NOT NULL DEFAULT 0,
      "MaxAge" integer NOT NULL DEFAULT 0,
      "Category" text,
      "ImageUrl" text,
      "PlaceId" text,
      "Rating" double precision NOT NULL DEFAULT 0,
      "UpdatedAt" timestamptz NOT NULL DEFAULT NOW(),
      "IsDeleted" boolean NOT NULL DEFAULT false
    );
