apiVersion: apps/v1
kind: Deployment
metadata:
  name: activitiesapp-web
  namespace: sam-cael-final
  labels:
    app: activitiesapp-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activitiesapp-web
  template:
    metadata:
      labels:
        app: activitiesapp-web
    spec:
      containers:
      - name: activitiesapp-web
        image: samuelschuetz77/activitiesapp-web:h2c81
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ApiAddress
          value: "http://activitiesapp-api:81"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: APP_VERSION
          value: "h2c81"
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            memory: 400Mi
