apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: activitiesapp
data:
  datasources.yaml: |
    apiVersion: 1
    prune: true
    datasources:
      - name: prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false

      - name: loki
        type: loki
        uid: loki
        access: proxy
        url: http://loki:3100
        editable: false

      - name: google-cloud-monitoring
        type: stackdriver
        uid: gcm
        access: proxy
        editable: false
        jsonData:
          authenticationType: key
          defaultProject: activitiesapp-490113
          clientEmail: $__env{GCP_CLIENT_EMAIL}
          tokenUri: https://oauth2.googleapis.com/token
        secureJsonData:
          privateKey: $__env{GCP_PRIVATE_KEY}
