apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: activitiesapp
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - grafana.activor.duckdns.org
      secretName: wildcard-activor-tls
  rules:
    - host: grafana.activor.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
