apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: activitiesapp-api-pdb
  namespace: activitiesapp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: activitiesapp-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: activitiesapp-web-pdb
  namespace: activitiesapp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: activitiesapp-web
